name: Bug report
description: Fill out a bug report
body:
 - type: textarea
    attributes:
      label: Bug description
      description: Specify your problem
    validations:
      required: true
- type: dropdown
  attributes:
    label: Platform
    description: Specify your platform
    options:
    - Windows
    - macOS
    - iOS
    - Android
    default: 0
  validations:
    required: true
  
 