name: Bug report
description: Fill out a bug report
body:

 - type: textarea
    attributes:
      label: Bug description
      description: What happened? What did you expect to happen? Feel free to drop any screenshots in here.
      placeholder: I did this thing over here, and saw this error...
    validations:
      required: true

- type: dropdown
  attributes:
    label: Platform
    description: Specify your platform
    options:
    - Windows
    - macOS
    - iOS
    - Android
    default: 0
  validations:
    required: true
  
 